Repository sipe-team/3-1_spurt, pull requests merged in 2024-11, with the labels that each got.

#2 week1(희동): 1주차 학습
  activity/week1/ruthetum/README.md
  activity/week1/ruthetum/assets/latency-tps.png
  activity/week1/ruthetum/assets/latency-users.png
  activity/week1/ruthetum/assets/tps-users.png
  playground/ruthetum/.gitignore
  playground/ruthetum/app/case1/build.gradle.kts
  playground/ruthetum/app/case1/src/main/kotlin/team/sipe/spurt/app/case1/Case1Application.kt
  playground/ruthetum/app/case1/src/main/resources/application.yml
  playground/ruthetum/app/case1/src/test/kotlin/team/sipe/spurt/app/case1/Case1ApplicationTests.kt
  playground/ruthetum/app/case1/src/test/resources/application-test.yml
  playground/ruthetum/app/picker/build.gradle.kts
  playground/ruthetum/app/picker/src/main/kotlin/team/sipe/spurt/app/picker/Picker.kt
  playground/ruthetum/build.gradle.kts
  playground/ruthetum/gradle.properties
  playground/ruthetum/gradle/wrapper/gradle-wrapper.jar
  playground/ruthetum/gradle/wrapper/gradle-wrapper.properties
  playground/ruthetum/gradlew
  playground/ruthetum/gradlew.bat
  playground/ruthetum/practice/benchmark/README.md
  playground/ruthetum/practice/benchmark/build.gradle.kts
  playground/ruthetum/practice/benchmark/src/jmh/kotlin/team/sipe/spurt/practice/benchmark/SortingUtilsBenchmark.kt
  playground/ruthetum/practice/benchmark/src/jmh/kotlin/team/sipe/spurt/practice/benchmark/SortingUtilsSteps.kt
  playground/ruthetum/practice/benchmark/src/main/kotlin/team/sipe/spurt/practice/benchmark/SortingUtils.kt
  playground/ruthetum/practice/benchmark/src/test/kotlin/team/sipe/spurt/practice/benchmark/SortingUtilsTests.kt
  playground/ruthetum/practice/oom/build.gradle.kts
  playground/ruthetum/practice/oom/src/main/kotlin/team/sipe/spurt/practice/oom/CountryController.kt
  playground/ruthetum/practice/oom/src/main/kotlin/team/sipe/spurt/practice/oom/CountryService.kt
  playground/ruthetum/practice/oom/src/main/kotlin/team/sipe/spurt/practice/oom/OomApplication.kt
  playground/ruthetum/practice/oom/src/test/kotlin/team/sipe/spurt/practice/oom/OomApplicationTests.kt
  playground/ruthetum/settings.gradle.kts
  playground/ruthetum/support/build.gradle.kts
  playground/ruthetum/support/src/main/kotlin/team/sipe/spurt/support/.gitkeep
  playground/ruthetum/support/src/main/resources/.gitkeep
Labels: 코드, 활동

#1 1주차 추천 및 참고 문서 취합
  .asset/README.md
  recommend.md
Labels: 참고

#5 [WIP] week1(준용): 1주차 학습
  .asset/Load_Test_type.png
  activity/week1/devfancy/Performance-Concept.md
Labels: 활동

#3 week1(상준): 1주차 학습
  .asset/sangjun121/.gitkeep
  .asset/sangjun121/week1-1-1.png
  .asset/sangjun121/week1-1-2.png
  .asset/sangjun121/week1-1-3.png
  .asset/sangjun121/week1-2-1.png
  .asset/sangjun121/week1-2-2.png
  .asset/sangjun121/week1-2-3.webp
  .asset/sangjun121/week1-2-4.png
  .asset/sangjun121/week1-2-5.png
  .asset/sangjun121/week1-3-1.webp
  .asset/sangjun121/week1-3-2.png
  .asset/sangjun121/week1-3-3.png
  .asset/sangjun121/week1-4-1.png
  .asset/sangjun121/week1-4-2.png
  .asset/sangjun121/week1-4-3.webp
  .asset/sangjun121/week1-4-4.webp
  .asset/sangjun121/week1-4-5.png
  activity/week1/sangjun121/.gitkeep
  activity/week1/sangjun121/1. 웹-성능이란-무엇인가.md
  activity/week1/sangjun121/2. 소프트웨어-성능-테스트.md
  activity/week1/sangjun121/3. 주요-병목지점.md
  activity/week1/sangjun121/4. 성능-측정-도구.md
Labels: 활동

#6 week1(준환): 1주차 학습 활동
  activity/week1/itschrisjang/README.md
Labels: 활동

#4 week1(우재): 1주차 학습 활동
  .asset/kwj1270/week1-1.png
  .asset/kwj1270/week1-10.png
  .asset/kwj1270/week1-11.png
  .asset/kwj1270/week1-12.png
  .asset/kwj1270/week1-13.png
  .asset/kwj1270/week1-14.png
  .asset/kwj1270/week1-15.png
  .asset/kwj1270/week1-16.png
  .asset/kwj1270/week1-17.png
  .asset/kwj1270/week1-18.png
  .asset/kwj1270/week1-19.png
  .asset/kwj1270/week1-2.png
  .asset/kwj1270/week1-20.png
  .asset/kwj1270/week1-21.png
  .asset/kwj1270/week1-22.png
  .asset/kwj1270/week1-23.png
  .asset/kwj1270/week1-24.png
  .asset/kwj1270/week1-25.png
  .asset/kwj1270/week1-26.png
  .asset/kwj1270/week1-27.png
  .asset/kwj1270/week1-28.png
  .asset/kwj1270/week1-29.png
  .asset/kwj1270/week1-3.png
  .asset/kwj1270/week1-30.png
  .asset/kwj1270/week1-31.png
  .asset/kwj1270/week1-32.png
  .asset/kwj1270/week1-33.png
  .asset/kwj1270/week1-34.png
  .asset/kwj1270/week1-35.png
  .asset/kwj1270/week1-36.png
  .asset/kwj1270/week1-37.png
  .asset/kwj1270/week1-38.png
  .asset/kwj1270/week1-39.png
  .asset/kwj1270/week1-4.png
  .asset/kwj1270/week1-40.png
  .asset/kwj1270/week1-5.png
  .asset/kwj1270/week1-6.png
  .asset/kwj1270/week1-7.png
  .asset/kwj1270/week1-8.png
  .asset/kwj1270/week1-9.png
  activity/week1/kwj1270/README.md
  activity/week1/kwj1270/jvm-warmup.md
  activity/week1/kwj1270/perofomance-test-1.md
  activity/week1/kwj1270/perofomance-test-2.md
  activity/week1/kwj1270/perofomance-test-3.md
  activity/week1/kwj1270/perofomance-test-4.md
Labels: 활동

#9 [WIP] week1(영학): 1주차 학습 활동
  activity/week1/inspire12/Readme.md
  activity/week1/inspire12/images/img.png
Labels: 활동

#7 week1(지예): 1주차 학습
  activity/week1/yujiyea/images/responseTime.png
  activity/week1/yujiyea/images/tps.png
  activity/week1/yujiyea/성능.md
Labels: 활동

#19 week2(희동): 부하 테스트 및 모니터링
  activity/week2/ruthetum/.gitkeep
  activity/week2/ruthetum/README.md
  activity/week2/ruthetum/assets/grafana1.png
  activity/week2/ruthetum/assets/grafana2.png
  activity/week2/ruthetum/assets/intellij-profiler-manual1.png
  activity/week2/ruthetum/assets/intellij-profiler-manual2.png
  activity/week2/ruthetum/assets/intellij-profiler-manual3.png
  activity/week2/ruthetum/assets/intellij-profiler-manual4.png
  activity/week2/ruthetum/assets/intellij-profiler-manual5.png
  activity/week2/ruthetum/assets/intellij-profiler-manual6.png
  activity/week2/ruthetum/assets/intellij-profiler.png
  activity/week2/ruthetum/assets/visualvm-menu.png
  activity/week2/ruthetum/assets/visualvm-plugins.png
  activity/week2/ruthetum/assets/visualvm-profiler.png
  activity/week2/ruthetum/assets/visualvm-tab1.png
  activity/week2/ruthetum/assets/visualvm-tab2.png
  activity/week2/ruthetum/assets/visualvm-tab3.png
  activity/week2/ruthetum/docker-compose.yaml
  activity/week2/ruthetum/intellij-profiler.md
  activity/week2/ruthetum/script.js
Labels: 활동

#14 feat(우재): 2주차 과제 제출
  .asset/kwj1270/week2-1.png
  .asset/kwj1270/week2-2.png
  .asset/kwj1270/week2-3.png
  activity/week2/kwj1270/k6.md
  activity/week2/kwj1270/oom.js
  activity/week2/kwj1270/result.md
  playground/kwj1270/performance-poc/.gitattributes
  playground/kwj1270/performance-poc/.gitignore
  playground/kwj1270/performance-poc/build.gradle
  playground/kwj1270/performance-poc/docker-compose.yml
  playground/kwj1270/performance-poc/gradle/wrapper/gradle-wrapper.jar
  playground/kwj1270/performance-poc/gradle/wrapper/gradle-wrapper.properties
  playground/kwj1270/performance-poc/gradlew
  playground/kwj1270/performance-poc/gradlew.bat
  playground/kwj1270/performance-poc/infra/grafana/dashboards/jvm-micrometer.json
  playground/kwj1270/performance-poc/infra/grafana/dashboards/k6-dashboard_rev2.json
  playground/kwj1270/performance-poc/infra/grafana/dashboards/k6-load-testing-results_rev3.json
  playground/kwj1270/performance-poc/infra/grafana/dashboards/main.yaml
  playground/kwj1270/performance-poc/infra/grafana/dashboards/node-exporter.json
  playground/kwj1270/performance-poc/infra/grafana/datasources/datasource.yml
  playground/kwj1270/performance-poc/infra/k6/k6.sh
  playground/kwj1270/performance-poc/infra/k6/scripts/oom.js
  playground/kwj1270/performance-poc/infra/prometheus/prometheus.yml
  playground/kwj1270/performance-poc/settings.gradle
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/PerformancePocApplication.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/api/CountryQueryApi.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/application/CountryClient.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/application/CountryService.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/domain/Countries.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/domain/Country.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/infrastructure/CountryClientAdapter.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/infrastructure/CountryOkHttpClient.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/infrastructure/dto/ExternalCountryResponse.java
  playground/kwj1270/performance-poc/src/main/java/com/poc/performance/infrastructure/mapper/CountryMapper.java
  playground/kwj1270/performance-poc/src/main/resources/application.yml
  playground/kwj1270/performance-poc/src/test/java/com/poc/performance/PerformancePocApplicationTests.java
Labels: 코드, 활동

#13 week2(준용): K6 학습 및 oom 예제 추가
  playground/devfancy/spring-performance/.gitattributes
  playground/devfancy/spring-performance/.gitignore
  playground/devfancy/spring-performance/build.gradle
  playground/devfancy/spring-performance/docker/docker-compose.yml
  playground/devfancy/spring-performance/gradle/wrapper/gradle-wrapper.jar
  playground/devfancy/spring-performance/gradle/wrapper/gradle-wrapper.properties
  playground/devfancy/spring-performance/gradlew
  playground/devfancy/spring-performance/gradlew.bat
  playground/devfancy/spring-performance/img/grafana-dashboard.png
  playground/devfancy/spring-performance/img/technology_docker_desktop_grafana_k6.png
  playground/devfancy/spring-performance/img/technology_grafana_k6.png
  playground/devfancy/spring-performance/img/technology_k6_Constant_VUs_Result.png
  playground/devfancy/spring-performance/k6-concept.md
  playground/devfancy/spring-performance/k6-scripts/first_scripts.js
  playground/devfancy/spring-performance/k6-scripts/oom_scripts.js
  playground/devfancy/spring-performance/settings.gradle
  playground/devfancy/spring-performance/src/main/java/com/example/springperformance/CountryClient.java
  playground/devfancy/spring-performance/src/main/java/com/example/springperformance/CountryController.java
  playground/devfancy/spring-performance/src/main/java/com/example/springperformance/CountryResponse.java
  playground/devfancy/spring-performance/src/main/java/com/example/springperformance/CountryService.java
  playground/devfancy/spring-performance/src/main/java/com/example/springperformance/ExternalCountryResponse.java
  playground/devfancy/spring-performance/src/main/java/com/example/springperformance/SpringPerformanceApplication.java
  playground/devfancy/spring-performance/src/main/resources/application.properties
  playground/devfancy/spring-performance/src/test/java/com/example/springperformance/SpringPerformanceApplicationTests.java
Labels: 코드, 활동

#24 week3(우재): 3주차 프로젝트
  playground/kwj1270/commerce/.gitattributes
  playground/kwj1270/commerce/.gitignore
  playground/kwj1270/commerce/build.gradle
  playground/kwj1270/commerce/delivery/build.gradle
  playground/kwj1270/commerce/delivery/src/main/java/team/sipe/commerce/delivery/DeliveryApplication.java
  playground/kwj1270/commerce/delivery/src/main/java/team/sipe/commerce/delivery/delivery/api/FakeDeliveryApi.java
  playground/kwj1270/commerce/delivery/src/main/java/team/sipe/commerce/delivery/delivery/domain/Delivery.java
  playground/kwj1270/commerce/delivery/src/main/java/team/sipe/commerce/delivery/delivery/domain/DeliveryAddress.java
  playground/kwj1270/commerce/delivery/src/main/java/team/sipe/commerce/delivery/delivery/domain/DeliveryStatus.java
  playground/kwj1270/commerce/delivery/src/main/resources/application.yml
  playground/kwj1270/commerce/delivery/src/test/java/team/sipe/commerce/delivery/DeliveryApplicationTests.java
  playground/kwj1270/commerce/display/build.gradle
  playground/kwj1270/commerce/display/src/main/java/team/sipe/commerce/display/DisplayApi.java
  playground/kwj1270/commerce/display/src/main/java/team/sipe/commerce/display/DisplayApplication.java
  playground/kwj1270/commerce/display/src/main/java/team/sipe/commerce/display/application/DeliveryClient.java
  playground/kwj1270/commerce/display/src/main/java/team/sipe/commerce/display/application/OrderClient.java
  playground/kwj1270/commerce/display/src/main/java/team/sipe/commerce/display/infrastructure/DeliveryHttpClient.java
  playground/kwj1270/commerce/display/src/main/java/team/sipe/commerce/display/infrastructure/OrderHttpClient.java
  playground/kwj1270/commerce/display/src/main/resources/application.properties
  playground/kwj1270/commerce/display/src/test/java/team/sipe/commerce/display/DisplayApplicationTests.java
  playground/kwj1270/commerce/gradle/wrapper/gradle-wrapper.jar
  playground/kwj1270/commerce/gradle/wrapper/gradle-wrapper.properties
  playground/kwj1270/commerce/gradlew
  playground/kwj1270/commerce/gradlew.bat
  playground/kwj1270/commerce/order/build.gradle
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/OrderApplication.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/aggregation/UserOrderInfoApi.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/api/FakeOrderApi.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/Order.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/OrderLineItem.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/OrderLineItems.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/OrderOption.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/OrderOptionGroup.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/OrderPaymentMethod.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/OrderStatus.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/order/domain/Price.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/Refund.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/RefundMethod.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/RefundPrice.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/RefundProduct.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/RefundProductStatus.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/RefundProducts.java
  playground/kwj1270/commerce/order/src/main/java/team/sipe/commerce/order/refund/domain/RefundStatus.java
  playground/kwj1270/commerce/order/src/main/resources/application.properties
  playground/kwj1270/commerce/order/src/test/java/team/sipe/commerce/order/OrderApplicationTests.java
  playground/kwj1270/commerce/settings.gradle
  playground/kwj1270/commerce/shop/build.gradle
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/ProductApplication.java
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/product/FakeProductApi.java
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/product/domain/Price.java
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/product/domain/Product.java
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/product/domain/ProductOption.java
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/product/domain/ProductOptionGroup.java
  playground/kwj1270/commerce/shop/src/main/java/team/sipe/commerce/shop/shop/domain/Shop.java
  playground/kwj1270/commerce/shop/src/main/resources/application.properties
  playground/kwj1270/commerce/shop/src/test/java/team/sipe/commerce/shop/ProductApplicationTests.java
Labels: 코드, 활동

#27 week3(상준): 3주차 학습 - 주문 조회 API의 성능 개선
  playground/sangjun121/.gitkeep
  playground/sangjun121/java-springboot-order-perf-optimizer/.gitattributes
  playground/sangjun121/java-springboot-order-perf-optimizer/.gitignore
  playground/sangjun121/java-springboot-order-perf-optimizer/build.gradle
  playground/sangjun121/java-springboot-order-perf-optimizer/gradle/wrapper/gradle-wrapper.jar
  playground/sangjun121/java-springboot-order-perf-optimizer/gradle/wrapper/gradle-wrapper.properties
  playground/sangjun121/java-springboot-order-perf-optimizer/gradlew
  playground/sangjun121/java-springboot-order-perf-optimizer/gradlew.bat
  playground/sangjun121/java-springboot-order-perf-optimizer/settings.gradle
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/JavaSpringbootOrderPerfOptimizerApplication.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/application/OrderService.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/application/dto/OrderDetailsResponse.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/common/BaseEntity.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/Delivery.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/Order.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/OrderProduct.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/OrderStatus.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/Payment.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/Product.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/Refund.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/RefundMethodName.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/RefundStatus.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/repository/DeliveryRepository.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/repository/OrderRepository.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/repository/PaymentRepository.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/repository/ProductRepository.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/domain/repository/RefundRepository.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/dto/DeliveryDetailsResponse.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/dto/OrderItemResponse.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/dto/ProductBundleDetailsResponse.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/dto/ProductDetailsResponse.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/dto/RefundDetailsDto.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/presentation/OrderController.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/resources/application.yml
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/resources/data.sql
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/resources/schema.sql
  playground/sangjun121/java-springboot-order-perf-optimizer/src/test/java/com/java/springboot/order/perf/JavaSpringbootOrderPerfOptimizerApplicationTests.java
Labels: 코드, 활동

#36 week4(영학) - mysql로 포팅
  activity/week4/inspire12/README.md
  playground/inspire12/performance-testing-architecture/k6-testing/js/week1/get-test.js
  playground/inspire12/performance-testing-architecture/k6-testing/js/week1/result
  playground/inspire12/performance-testing-architecture/k6-testing/js/week1/testing-result
Labels: 코드, 활동

#35 week4(준용): 주문 API 설계 - 성능 개선
  playground/devfancy/commerce/monitoring/k6.script/order.js
Labels: 코드, 활동

#34 week4(상준): 주문API 설계 시 비동기 메소드와 쿼리 최적화
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/JavaSpringbootOrderPerfOptimizerApplication.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/application/OrderService.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/application/dto/OrderDetailsResponse.java
  playground/sangjun121/java-springboot-order-perf-optimizer/src/main/java/com/order/perf/config/AsyncConfig.java
Labels: 코드, 활동
